version: "3.8"

services:
  mongodb:
    image: mongo
    env_file: ./.env
    restart: unless-stopped
    ports:
      #- $DB_LOCAL_PORT:$DB_DOCKER_PORT
      - "27017:27017"
    volumes:
      - db:/data/db

  node-app:
    build: .

    image: node-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
    ports:
      # - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - "8082:8082"
    depends_on:
      - mongodb

volumes:
  db:
